services:
  backend:
    build: .           # <-- just a dot, not ./backend
    command: "node server.js"
    volumes:
      - ./:/backend       # <-- updated to match WORKDIR in Dockerfile

    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env.docker         # this file should exist in backend/

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
